/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Exam {
  'id' : bigint,
  'title' : string,
  'category' : string,
  'examDate' : string,
}
export interface ExamRegistration {
  'user' : Principal,
  'timestamp' : Time,
  'examId' : bigint,
}
export interface Profile {
  'password' : string,
  'fullName' : string,
  'email' : string,
  'mobile' : string,
}
export type Time = bigint;
export interface UserProfile {
  'fullName' : string,
  'email' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllExams' : ActorMethod<[], Array<Exam>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExamsByCategory' : ActorMethod<[string], Array<Exam>>,
  'getMyProfile' : ActorMethod<[], Profile>,
  'getMyRegistrations' : ActorMethod<[], Array<ExamRegistration>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], Profile>,
  'register' : ActorMethod<[string, string, string, string], undefined>,
  'registerForExam' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unregisterFromExam' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];