/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Exam = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'category' : IDL.Text,
  'examDate' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'mobile' : IDL.Text,
});
export const Profile = IDL.Record({
  'password' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'mobile' : IDL.Text,
});
export const Time = IDL.Int;
export const ExamRegistration = IDL.Record({
  'user' : IDL.Principal,
  'timestamp' : Time,
  'examId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExamsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Exam)], ['query']),
  'getMyProfile' : IDL.Func([], [Profile], ['query']),
  'getMyRegistrations' : IDL.Func([], [IDL.Vec(ExamRegistration)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [Profile], []),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'registerForExam' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unregisterFromExam' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Exam = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'category' : IDL.Text,
    'examDate' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const Profile = IDL.Record({
    'password' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const Time = IDL.Int;
  const ExamRegistration = IDL.Record({
    'user' : IDL.Principal,
    'timestamp' : Time,
    'examId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExamsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Exam)], ['query']),
    'getMyProfile' : IDL.Func([], [Profile], ['query']),
    'getMyRegistrations' : IDL.Func([], [IDL.Vec(ExamRegistration)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [Profile], []),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'registerForExam' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unregisterFromExam' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };